AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repository for dad-pass application

Parameters:
    StageName:
        Type: String
        Default: dev
        AllowedValues:
            - dev
            - staging
            - prod
        Description: Deployment stage

    ImageRetentionCount:
        Type: Number
        Default: 10
        Description: Number of images to retain in the repository

Resources:
    ECRRepository:
        Type: AWS::ECR::Repository
        Properties:
            RepositoryName: !Sub 'dad-pass-${StageName}'
            ImageScanningConfiguration:
                ScanOnPush: true
            ImageTagMutability: MUTABLE
            LifecyclePolicy:
                LifecyclePolicyText: !Sub |
                    {
                      "rules": [
                        {
                          "rulePriority": 1,
                          "description": "Keep last ${ImageRetentionCount} images",
                          "selection": {
                            "tagStatus": "any",
                            "countType": "imageCountMoreThan",
                            "countNumber": ${ImageRetentionCount}
                          },
                          "action": {
                            "type": "expire"
                          }
                        }
                      ]
                    }
            Tags:
                - Key: Application
                  Value: dad-pass
                - Key: Stage
                  Value: !Ref StageName

Outputs:
    RepositoryUri:
        Description: ECR Repository URI
        Value: !GetAtt ECRRepository.RepositoryUri
        Export:
            Name: !Sub '${AWS::StackName}-RepositoryUri'

    RepositoryArn:
        Description: ECR Repository ARN
        Value: !GetAtt ECRRepository.Arn
        Export:
            Name: !Sub '${AWS::StackName}-RepositoryArn'

    RepositoryName:
        Description: ECR Repository Name
        Value: !Ref ECRRepository
        Export:
            Name: !Sub '${AWS::StackName}-RepositoryName'
